@api = http://localhost:9000/User

### get user
POST http://localhost:9000/UserLogin
Content-Type: application/json

{ 
  "CONTRASEÑA": "123456",
"USUARIO": "cambio"
}

####     
GET {{api}}


###
DELETE  {{api}}/5

###
PUT {{api}}
Content-Type: application/json

{ 
    "ID": "1",
    "USUARIO": "cambio",
    "CONTRASEÑA": "123456",
    "NOMBRE": "Pablo",
    "CORREO": "hola@gmail.com"
}

###
POST http://localhost:9000/Apuntes/User
Content-Type: application/json

{ 
  "ID": "1"

}
###
POST http://localhost:9000/List/IDPDF
Content-Type: application/json

{ 
    "ID":"1477",
    "ID_PDF":"124"

}