@api = http://localhost:4000/User

### get user
POST http://localhost:4000/UserLogin
Content-Type: application/json

{ 
  "USUARIO": "admin",
  "CONTRASEÑA":"123456"
}

####
GET {{api}}


###
DELETE  {{api}}/370